apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-site
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: adongy/hostname-docker
        ports:
        - containerPort: 80