apiVersion: v1
kind: Service
metadata:
  name: service-name-for-the-app
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 80